### PR TITLE
Update NOTES.txt

### PR DESCRIPTION
**Pull request by JaredTan95**

### CODE REVIEW

**Comment by wu-sheng** [comment]
Is this a bug requiring to be included in 1.0 release?

**Comment by JaredTan95** [comment]
> Is this a bug requiring to be included in 1.0 release?

not a bug actually. just commands does not works if users use `port-forward` way to Visit skywalking-ui.

**Comment by wu-sheng** [comment]
My point is, do we need a new git tag? Considering today is at test staging, but tag is already done.

**Comment by JaredTan95** [comment]
I got your point, we need a new tag. FYI @innerpeacez

**Comment by innerpeacez** [comment]
In fact, even if we add a namespace, there is no way to access it directly, it can only serve as a reminder, so I want to include it in the next tag. @JaredTan95

**Comment by JaredTan95** [comment]
OK

**Pull request merged**
