### PR TITLE
The init job should be executed first before oap start.

### PR DESCRIPTION
**Pull request by innerpeacez**
The init job should be executed first before oap start.

### CODE REVIEW

**Review by kezhenxu94 — CHANGES_REQUESTED** [review]
This is wrong, init job requires some resources that must be applied first, using `pre-hook` the installation will be in dead lock state, `init-job` is waiting for other resources like service account, but service account resource is waiting for the `pre-hook` to complete

**Comment by innerpeacez** [comment]
> This is wrong, init job requires some resources that must be applied first, using `pre-hook` the installation will be in dead lock state, `init-job` is waiting for other resources like service account, but service account resource is waiting for the `pre-hook` to complete

hi, we have two ways to execute init-job
1: Let all resources that need to be started be executed with init-job first.
2: Start oap after init-job.

The first way is relatively complicated, so I adopted the second way.

**Comment by kezhenxu94** [comment]
> > This is wrong, init job requires some resources that must be applied first, using `pre-hook` the installation will be in dead lock state, `init-job` is waiting for other resources like service account, but service account resource is waiting for the `pre-hook` to complete
> 
> hi, we have two ways to execute init-job 1: Let all resources that need to be started be executed with init-job first. 2: Start oap after init-job.
> 
> The first way is relatively complicated, so I adopted the second way.

I don't personally want to use the helm hooks to manage the resource dependency, because in Kubernetes we don't need to manage the dependency too strictly, they will finally get in ready. The only reason why I introduced helm hook is to allow upgrading without having to delete all resource. See https://github.com/apache/skywalking-kubernetes/pull/95 and https://github.com/apache/skywalking/discussions/9290

**Comment by innerpeacez** [comment]
I don't want oap to restart before initjob execution is completed, but after using startupProbe(https://github.com/apache/skywalking-kubernetes/pull/108), this phenomenon may be alleviated. If you feel that we don't need to manage dependencies, you can close this PR. @kezhenxu94 thanks.

**Comment by innerpeacez** [comment]
Sorry. There are some problems with hook.

**Pull request closed without merging**
