### PR TITLE
update oap address in ui deployment.

### PR DESCRIPTION
**Pull request by JaredTan95**
after https://github.com/apache/skywalking/pull/7220 merged

### CODE REVIEW

**Review by kezhenxu94 — APPROVED** [review]

**Review by innerpeacez — APPROVED** [review]

**Comment by wu-sheng** [comment]
This merged before expected. We need to say next helm release for 8.7.0+ only. Could you update document?

**Comment by wu-sheng** [comment]
Next should be 4.1.0, and we should keep both releases on website.

**Comment by JaredTan95** [comment]
> This merged before expected. We need to say next helm release for 8.7.0+ only. Could you update document?

okay, i will update the docs within update skywalking main repo commit

**Comment by kezhenxu94** [comment]
> This merged before expected. We need to say next helm release for 8.7.0+ only. Could you update document?

Adding the http schema in the env var should not impact previous version, no? @JaredTan95

**Comment by JaredTan95** [comment]
> > This merged before expected. We need to say next helm release for 8.7.0+ only. Could you update document?
> 
> Adding the http schema in the env var should not impact previous version, no? @JaredTan95

for my understanding,  not works  well when adding  http schema  in pre versions.

**Comment by JaredTan95** [comment]
ref https://cloud.spring.io/spring-cloud-netflix/multi/multi__router_and_filter_zuul.html, 

```yaml
myusers-service:
  ribbon:
    NIWSServerListClassName: com.netflix.loadbalancer.ConfigurationBasedServerList
    listOfServers: https://example1.com,http://example2.com
    ConnectTimeout: 1000
    ReadTimeout: 3000
    MaxTotalHttpConnections: 500
    MaxConnectionsPerHost: 100
```

add http in pre versions looks work

**Comment by kezhenxu94** [comment]
> ref https://cloud.spring.io/spring-cloud-netflix/multi/multi__router_and_filter_zuul.html,
> 
> ```yaml
> myusers-service:
>   ribbon:
>     NIWSServerListClassName: com.netflix.loadbalancer.ConfigurationBasedServerList
>     listOfServers: https://example1.com,http://example2.com
>     ConnectTimeout: 1000
>     ReadTimeout: 3000
>     MaxTotalHttpConnections: 500
>     MaxConnectionsPerHost: 100
> ```
> 
> add http in pre versions looks work

Yes that’s what I had expected. So we don’t need any doc about this change

**Comment by kezhenxu94** [comment]
Also. Because the CI in this repo uses previous versions to test, and they passed.

**Comment by wu-sheng** [comment]
Thank you for clarification

**Pull request merged**
