### PR TITLE
2.0.0 change

### PR DESCRIPTION
**Pull request by innerpeacez**

### CODE REVIEW

**Comment by wu-sheng** [comment]
@innerpeacez Do you submit the wrong request to INFRA? It requires `.github/workflows/chart-deploy-ci.yaml ` task. We can't merge the PR untill INFRA changed it correctly.

**Comment by innerpeacez** [comment]
Already feedback.And I found that the `legacy-helm-chart` branch is gone. I don't know why,and I do n’t remember I deleted it.

**Comment by wu-sheng** [comment]
> Already feedback.And I found that the legacy-helm-chart branch is gone. I don't know why,and I do n’t remember I deleted it.

Yes. Super strange. I didn't delete it too.

**Comment by wu-sheng** [comment]
As those are not Apache release, this is not a big issue. But please remove those words from the readme to avoid mislead.

**Comment by innerpeacez** [comment]
> As those are not Apache release, this is not a big issue. But please remove those words from the readme to avoid mislead.

I still have this branch locally, resubmit this branch?

**Comment by wu-sheng** [comment]
> I still have this branch locally, resubmit this branch?

You can, and request the branch protection this time.

**Comment by innerpeacez** [comment]
Done.The strange thing is that the reply before `infra` was that both the master branch and the legacy-helm-chart branch are protected

**Comment by wu-sheng** [comment]
If it is protected, ask Infra about this. We can't delete once it is protected.

**Pull request merged**
