### PR TITLE
Upgrade ElasticSearch Helm Chart dependency version

### PR DESCRIPTION
**Pull request by kezhenxu94**

### CODE REVIEW

**Review by wu-sheng — APPROVED** [review]

**Comment by wu-sheng** [comment]
It seems we have a different case using OAP 8.6.0?

**Comment by kezhenxu94** [comment]
> It seems we have a different case using OAP 8.6.0?

We just announced EOF of 8.x, I'll just remove the test in this repo.

**Review by wu-sheng — APPROVED** [review]

**Comment by zalintyre** [comment]
Thank you for implementing this so quick! When can I expect the chart in the registry to be updated?

**Comment by kezhenxu94** [comment]
> Thank you for implementing this so quick! When can I expect the chart in the registry to be updated?

I hope I can cut release 4.4.0 this or next week but before that if you want to test you can use this https://github.com/apache/skywalking-kubernetes/pkgs/container/skywalking-kubernetes%2Fskywalking-helm. Note this is a snapshot registry so the version format is a little bit weird

**Pull request merged**
