### PR TITLE
Chart Release Deploy CI

### PR DESCRIPTION
**Pull request by innerpeacez**

### CODE REVIEW

**Comment by wu-sheng** [comment]
You need to merge an empty github action YAML first to active it.

**Comment by wu-sheng** [comment]
Set a new pull request of `.github/workflows/chart-deploy-ci.yaml `  excluding the real CI steps.

**Comment by innerpeacez** [comment]
got it @wu-sheng

**Comment by wu-sheng** [comment]
After your CI setup ready, take this as a refer, https://issues.apache.org/jira/browse/INFRA-19883. Submit a new JIRA ticket to set this for this repo.

**Comment by innerpeacez** [comment]
@wu-sheng @hanahmily My idea for Chart Release CI is to only verify whether oap ui es and so on can be deployed to the k8s cluster through chart. For the verification of availability after deployment, I want to do it in the [main repo](https://github.com/apache/skywalking),The main repo has e2e for easy testing

**Comment by innerpeacez** [comment]
done. @wu-sheng

**Comment by wu-sheng** [comment]
This is major checking the deployment, right? Are ES6 and ES7 both deployed?

**Comment by innerpeacez** [comment]
@wu-sheng Yes, major check deployment, ES6 and ES7 both passed.

**Comment by innerpeacez** [comment]
> And this task is for the existing 1.1.0(referring SkyWalking 6.6.0 release images), right?

Right now, starting with SW 7.0.0 will also work.

**Comment by wu-sheng** [comment]
Basically, yes. My question came from, I don't find out the image version update logs.

**Comment by innerpeacez** [comment]
> Basically, yes. My question came from, I don't find out the image version update logs.

Yes, i haven't started the release of 2.0.0.

**Pull request merged**
