### PR TITLE
Prepare for release 4.2.0

### PR DESCRIPTION
**Pull request by mrproliu**

### CODE REVIEW

**Review by kezhenxu94 — APPROVED** [review]

**Review by wu-sheng — APPROVED** [review]

**Comment by wu-sheng** [comment]
Please try to add a new e2e about Satellite installed with the image matching release(0.4.0) commit it.

**Review by hanahmily — APPROVED** [review]
LGTM

**Comment by mrproliu** [comment]
> Please try to add a new e2e about Satellite installed with the image matching release(0.4.0) commit it.

I think this will have to wait until satellite release 0.4.0 is complete. After the Satellite release process is finished, I will create other PR to add them.

**Comment by wu-sheng** [comment]
OK, we are using the official docker hug to testing? What does `
Test / Istio+Envoy Access Log Service(recent) (pull_request)` mean? Which version does it refer?

**Comment by mrproliu** [comment]
> OK, we are using the official docker hug to testing? What does ` Test / Istio+Envoy Access Log Service(recent) (pull_request)` mean? Which version does it refer?

That's working for testing the component haven't released version. I think after the Satellite is released, we could remove this, only test with the official release version.

**Comment by wu-sheng** [comment]
Agree, for helm repository, it is better to the latest release version.

**Pull request merged**
